### ISSUE TITLE
Update to 1.21.4 Please

### ISSUE THREAD

**Issue by sternschnaube** [abigailfails/HelpfulHitboxes#3]
net.fabricmc.loader.impl.FormattedException: java.lang.NoSuchMethodError: 'net.minecraft.class_7172$class_7307 net.minecraft.class_7172.method_42717(net.minecraft.class_2561)'
	at Not Enough Crashes deobfuscated stack trace.(1.19.3+build.4)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:463)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
Caused by: java.lang.NoSuchMethodError: 'net.minecraft.class_7172$class_7307 net.minecraft.class_7172.method_42717(net.minecraft.class_2561)'
	at com.github.abigailfails.helpfulhitboxes.ModOptions.<clinit>(ModOptions.java:18)
	at net.minecraft.block.AbstractBlock$AbstractBlockState.handler$fch000$modifyGetShape(AbstractBlock:3204)
	at net.minecraft.block.AbstractBlock$AbstractBlockState.getOutlineShape(AbstractBlock)
	at net.minecraft.block.AbstractBlock$AbstractBlockState.getOutlineShape(AbstractBlock:883)
	at net.minecraft.block.Block.isTranslucent(Block:311)
	at net.minecraft.block.AbstractBlock$AbstractBlockState$ShapeCache.<init>(AbstractBlock:1143)
	at net.minecraft.block.AbstractBlock$AbstractBlockState.initShapeCache(AbstractBlock:740)
	at net.minecraft.block.Blocks.<clinit>(Blocks:1132)
	at net.minecraft.block.FireBlock.registerDefaultFlammables(FireBlock:325)
	at net.minecraft.Bootstrap.initialize(Bootstrap:46)
	at net.minecraft.client.main.Main.main(Main:161)
	at net.minecraft.client.main.Main.main(Main:51)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	... 2 more

**Comment by venaminecraft** [comment]
Any plans on this @flowerfugue? 
Would love to play with that mod again 😊 
And could you please publish the mod on Modrinth as well?
